name: Create Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci && mkdir -p ./bin
      - run: npm run package
      - uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: ./bin/one-nord.vsix
