name: Deploy Release
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
        description: Tag to checkout and publish
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - env:
          VSCE_PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
        run: npm run vsce-publish -- -p $VSCE_PUBLISHER_TOKEN
