name: Release please

on:
  push:
    branches:
      - main
    paths:
      - src/one-nord.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
